Citizen.CreateThread(function()
	AddTextEntryByHash(GetHashKey("vwtouareg_rollcage"),"0")
	AddTextEntryByHash(GetHashKey("vwtouareg_roof_1"),"1")
	AddTextEntryByHash(GetHashKey("vwtouareg_spoiler_1"),"2")

	AddTextEntryByHash(GetHashKey("mercedesg65_rollcage"),"0")
	AddTextEntryByHash(GetHashKey("mercedesg65_wing_1"),"1")
	AddTextEntryByHash(GetHashKey("mercedesg65_wing_2"),"2")

	AddTextEntryByHash(GetHashKey("corvettec7_wing_1"),"0")

	AddTextEntryByHash(GetHashKey("m8competition_exhaust"),"0")
	AddTextEntryByHash(GetHashKey("m8competition_wing_1"),"1")
	AddTextEntryByHash(GetHashKey("m8competition_wing_2"),"2")

	AddTextEntryByHash(GetHashKey("audir8_rollcage"),"0")
	AddTextEntryByHash(GetHashKey("audir8_wing_1"),"1")

	AddTextEntryByHash(GetHashKey("rangerover_exh2"),"0")
	AddTextEntryByHash(GetHashKey("rangerover_grill"),"1")
	AddTextEntryByHash(GetHashKey("rangerover_hood_1"),"2")
	AddTextEntryByHash(GetHashKey("rangerover_rollcage"),"3")
	AddTextEntryByHash(GetHashKey("rangerover_roof"),"4")
	AddTextEntryByHash(GetHashKey("rangerover_skirt"),"5")
	AddTextEntryByHash(GetHashKey("rangerover_wing_1"),"6")
	AddTextEntryByHash(GetHashKey("rangerover_wing_2"),"7")

	AddTextEntryByHash(GetHashKey("raptor_csign_a0"),"0")
	AddTextEntryByHash(GetHashKey("raptor_csign_a1"),"1")
	AddTextEntryByHash(GetHashKey("raptor_csign_a2"),"2")
	AddTextEntryByHash(GetHashKey("raptor_csign_a3"),"3")
	AddTextEntryByHash(GetHashKey("raptor_csign_a4"),"4")
	AddTextEntryByHash(GetHashKey("raptor_csign_a5"),"5")
	AddTextEntryByHash(GetHashKey("raptor_csign_a6"),"6")
	AddTextEntryByHash(GetHashKey("raptor_csign_a7"),"7")
	AddTextEntryByHash(GetHashKey("raptor_csign_a8"),"8")
	AddTextEntryByHash(GetHashKey("raptor_csign_a9"),"9")
	AddTextEntryByHash(GetHashKey("raptor_csign_b0"),"0")
	AddTextEntryByHash(GetHashKey("raptor_csign_b1"),"1")
	AddTextEntryByHash(GetHashKey("raptor_csign_b2"),"2")
	AddTextEntryByHash(GetHashKey("raptor_csign_b3"),"3")
	AddTextEntryByHash(GetHashKey("raptor_csign_b4"),"4")
	AddTextEntryByHash(GetHashKey("raptor_csign_b5"),"5")
	AddTextEntryByHash(GetHashKey("raptor_csign_b6"),"6")
	AddTextEntryByHash(GetHashKey("raptor_csign_b7"),"7")
	AddTextEntryByHash(GetHashKey("raptor_csign_b8"),"8")
	AddTextEntryByHash(GetHashKey("raptor_csign_b9"),"9")
	AddTextEntryByHash(GetHashKey("raptor_csign_c0"),"0")
	AddTextEntryByHash(GetHashKey("raptor_csign_c1"),"1")
	AddTextEntryByHash(GetHashKey("raptor_csign_c2"),"2")
	AddTextEntryByHash(GetHashKey("raptor_csign_c3"),"3")
	AddTextEntryByHash(GetHashKey("raptor_csign_c4"),"4")
	AddTextEntryByHash(GetHashKey("raptor_csign_c5"),"5")
	AddTextEntryByHash(GetHashKey("raptor_csign_c6"),"6")
	AddTextEntryByHash(GetHashKey("raptor_csign_c7"),"7")
	AddTextEntryByHash(GetHashKey("raptor_csign_c8"),"8")
	AddTextEntryByHash(GetHashKey("raptor_csign_c9"),"9")

	AddTextEntryByHash(GetHashKey("dodge_csign_a0"),"0")
	AddTextEntryByHash(GetHashKey("dodge_csign_a1"),"1")
	AddTextEntryByHash(GetHashKey("dodge_csign_a2"),"2")
	AddTextEntryByHash(GetHashKey("dodge_csign_a3"),"3")
	AddTextEntryByHash(GetHashKey("dodge_csign_a4"),"4")
	AddTextEntryByHash(GetHashKey("dodge_csign_a5"),"5")
	AddTextEntryByHash(GetHashKey("dodge_csign_a6"),"6")
	AddTextEntryByHash(GetHashKey("dodge_csign_a7"),"7")
	AddTextEntryByHash(GetHashKey("dodge_csign_a8"),"8")
	AddTextEntryByHash(GetHashKey("dodge_csign_a9"),"9")
	AddTextEntryByHash(GetHashKey("dodge_csign_b0"),"0")
	AddTextEntryByHash(GetHashKey("dodge_csign_b1"),"1")
	AddTextEntryByHash(GetHashKey("dodge_csign_b2"),"2")
	AddTextEntryByHash(GetHashKey("dodge_csign_b3"),"3")
	AddTextEntryByHash(GetHashKey("dodge_csign_b4"),"4")
	AddTextEntryByHash(GetHashKey("dodge_csign_b5"),"5")
	AddTextEntryByHash(GetHashKey("dodge_csign_b6"),"6")
	AddTextEntryByHash(GetHashKey("dodge_csign_b7"),"7")
	AddTextEntryByHash(GetHashKey("dodge_csign_b8"),"8")
	AddTextEntryByHash(GetHashKey("dodge_csign_b9"),"9")
	AddTextEntryByHash(GetHashKey("dodge_csign_c0"),"0")
	AddTextEntryByHash(GetHashKey("dodge_csign_c1"),"1")
	AddTextEntryByHash(GetHashKey("dodge_csign_c2"),"2")
	AddTextEntryByHash(GetHashKey("dodge_csign_c3"),"3")
	AddTextEntryByHash(GetHashKey("dodge_csign_c4"),"4")
	AddTextEntryByHash(GetHashKey("dodge_csign_c5"),"5")
	AddTextEntryByHash(GetHashKey("dodge_csign_c6"),"6")
	AddTextEntryByHash(GetHashKey("dodge_csign_c7"),"7")
	AddTextEntryByHash(GetHashKey("dodge_csign_c8"),"8")
	AddTextEntryByHash(GetHashKey("dodge_csign_c9"),"9")

	AddTextEntryByHash(GetHashKey("crownvic_csign_a0"),"0")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a1"),"1")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a2"),"2")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a3"),"3")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a4"),"4")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a5"),"5")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a6"),"6")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a7"),"7")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a8"),"8")
	AddTextEntryByHash(GetHashKey("crownvic_csign_a9"),"9")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b0"),"0")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b1"),"1")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b2"),"2")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b3"),"3")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b4"),"4")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b5"),"5")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b6"),"6")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b7"),"7")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b8"),"8")
	AddTextEntryByHash(GetHashKey("crownvic_csign_b9"),"9")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c0"),"0")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c1"),"1")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c2"),"2")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c3"),"3")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c4"),"4")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c5"),"5")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c6"),"6")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c7"),"7")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c8"),"8")
	AddTextEntryByHash(GetHashKey("crownvic_csign_c9"),"9")

	AddTextEntryByHash(GetHashKey("taurus_csign_a0"),"0")
	AddTextEntryByHash(GetHashKey("taurus_csign_a1"),"1")
	AddTextEntryByHash(GetHashKey("taurus_csign_a2"),"2")
	AddTextEntryByHash(GetHashKey("taurus_csign_a3"),"3")
	AddTextEntryByHash(GetHashKey("taurus_csign_a4"),"4")
	AddTextEntryByHash(GetHashKey("taurus_csign_a5"),"5")
	AddTextEntryByHash(GetHashKey("taurus_csign_a6"),"6")
	AddTextEntryByHash(GetHashKey("taurus_csign_a7"),"7")
	AddTextEntryByHash(GetHashKey("taurus_csign_a8"),"8")
	AddTextEntryByHash(GetHashKey("taurus_csign_a9"),"9")
	AddTextEntryByHash(GetHashKey("taurus_csign_b0"),"0")
	AddTextEntryByHash(GetHashKey("taurus_csign_b1"),"1")
	AddTextEntryByHash(GetHashKey("taurus_csign_b2"),"2")
	AddTextEntryByHash(GetHashKey("taurus_csign_b3"),"3")
	AddTextEntryByHash(GetHashKey("taurus_csign_b4"),"4")
	AddTextEntryByHash(GetHashKey("taurus_csign_b5"),"5")
	AddTextEntryByHash(GetHashKey("taurus_csign_b6"),"6")
	AddTextEntryByHash(GetHashKey("taurus_csign_b7"),"7")
	AddTextEntryByHash(GetHashKey("taurus_csign_b8"),"8")
	AddTextEntryByHash(GetHashKey("taurus_csign_b9"),"9")
	AddTextEntryByHash(GetHashKey("taurus_csign_c0"),"0")
	AddTextEntryByHash(GetHashKey("taurus_csign_c1"),"1")
	AddTextEntryByHash(GetHashKey("taurus_csign_c2"),"2")
	AddTextEntryByHash(GetHashKey("taurus_csign_c3"),"3")
	AddTextEntryByHash(GetHashKey("taurus_csign_c4"),"4")
	AddTextEntryByHash(GetHashKey("taurus_csign_c5"),"5")
	AddTextEntryByHash(GetHashKey("taurus_csign_c6"),"6")
	AddTextEntryByHash(GetHashKey("taurus_csign_c7"),"7")
	AddTextEntryByHash(GetHashKey("taurus_csign_c8"),"8")
	AddTextEntryByHash(GetHashKey("taurus_csign_c9"),"9")

	AddTextEntryByHash(GetHashKey("explorer_csign_a0"),"0")
	AddTextEntryByHash(GetHashKey("explorer_csign_a1"),"1")
	AddTextEntryByHash(GetHashKey("explorer_csign_a2"),"2")
	AddTextEntryByHash(GetHashKey("explorer_csign_a3"),"3")
	AddTextEntryByHash(GetHashKey("explorer_csign_a4"),"4")
	AddTextEntryByHash(GetHashKey("explorer_csign_a5"),"5")
	AddTextEntryByHash(GetHashKey("explorer_csign_a6"),"6")
	AddTextEntryByHash(GetHashKey("explorer_csign_a7"),"7")
	AddTextEntryByHash(GetHashKey("explorer_csign_a8"),"8")
	AddTextEntryByHash(GetHashKey("explorer_csign_a9"),"9")
	AddTextEntryByHash(GetHashKey("explorer_csign_b0"),"0")
	AddTextEntryByHash(GetHashKey("explorer_csign_b1"),"1")
	AddTextEntryByHash(GetHashKey("explorer_csign_b2"),"2")
	AddTextEntryByHash(GetHashKey("explorer_csign_b3"),"3")
	AddTextEntryByHash(GetHashKey("explorer_csign_b4"),"4")
	AddTextEntryByHash(GetHashKey("explorer_csign_b5"),"5")
	AddTextEntryByHash(GetHashKey("explorer_csign_b6"),"6")
	AddTextEntryByHash(GetHashKey("explorer_csign_b7"),"7")
	AddTextEntryByHash(GetHashKey("explorer_csign_b8"),"8")
	AddTextEntryByHash(GetHashKey("explorer_csign_b9"),"9")
	AddTextEntryByHash(GetHashKey("explorer_csign_c0"),"0")
	AddTextEntryByHash(GetHashKey("explorer_csign_c1"),"1")
	AddTextEntryByHash(GetHashKey("explorer_csign_c2"),"2")
	AddTextEntryByHash(GetHashKey("explorer_csign_c3"),"3")
	AddTextEntryByHash(GetHashKey("explorer_csign_c4"),"4")
	AddTextEntryByHash(GetHashKey("explorer_csign_c5"),"5")
	AddTextEntryByHash(GetHashKey("explorer_csign_c6"),"6")
	AddTextEntryByHash(GetHashKey("explorer_csign_c7"),"7")
	AddTextEntryByHash(GetHashKey("explorer_csign_c8"),"8")
	AddTextEntryByHash(GetHashKey("explorer_csign_c9"),"9")

	AddTextEntryByHash(GetHashKey("r6_exh_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("r6_exh_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("r6_lever"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("r6_lever_guard"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("r6_lph_led"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("r6_lph_led_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("r6_racing_kit"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("r6_rear_set"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("r6_single_seat"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("r6_windscreen_2"),"Tuning 10")

	AddTextEntryByHash(GetHashKey("r1_chain"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("r1_exh_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("r1_exh_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("r1_exh_3"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("r1_gard"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("r1_mgaurd"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("r1_null"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("r1_null2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("r1_race"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("r1_race1"),"Tuning 10")

	AddTextEntryByHash(GetHashKey("lancerevolution9_bumf_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumf_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumf_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumr_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumr_2"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumr_3"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("lancerevolution9_exh_1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("lancerevolution9_hood_1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("lancerevolution9_skirt_1"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("lancerevolution9_skirt_2"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("lancerevolution9_skirt_3"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("lancerevolution9_wing_1"),"Tuning 12")

	AddTextEntryByHash(GetHashKey("dodgechargerrt69_bonnet_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_bonnet_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_bonnet_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_hydro1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_hydro2"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_hydro3"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_hydro4"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_rollcage"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_splitter"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("dodgechargerrt69_wing"),"Tuning 10")

	AddTextEntryByHash(GetHashKey("bmwm4gts_bonnet_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("bmwm4gts_cage_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("bmwm4gts_doorl"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("bmwm4gts_doorr"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("bmwm4gts_exh1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("bmwm4gts_exh2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("bmwm4gts_exh3"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("bmwm4gts_roof_1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("bmwm4gts_roof_2"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("bmwm4gts_roof_3"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("bmwm4gts_roof_4"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_1"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_2"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_3"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_4"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_5"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_6"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_7"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_8"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_9"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("bmwm4gts_wing_10"),"Tuning 21")

	AddTextEntryByHash(GetHashKey("dodgechargersrt_bonnet_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bonnet_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperf_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperf_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperf_3"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperf_4"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperf_5"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperf_6"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperf_7"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperf_8"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperr_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperr_2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperr_3"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperr_4"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperr_5"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_bumperr_6"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_rearbadge_1"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_rearbadge_2"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_roof_1"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_sidebadge_1"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_sidebadge_2"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_skirt_1"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_skirt_2"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_skirt_3"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_spoiler_1"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_spoiler_2"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("dodgechargersrt_spoiler_3"),"Tuning 27")

	AddTextEntryByHash(GetHashKey("fordmustang_bumpf_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("fordmustang_bumpf_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("fordmustang_bumpr_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("fordmustang_bumpr_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("fordmustang_bumpr_3"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("fordmustang_bumpr_4"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("fordmustang_bumpr_5"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("fordmustang_cage_1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("fordmustang_cage_2"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("fordmustang_cage_3"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("fordmustang_exh"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("fordmustang_exh2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_1"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_2"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_3"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_4"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_5"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_6"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_7"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_8"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_9"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("fordmustang_hood_10"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("fordmustang_roof"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("fordmustang_roof_2"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("fordmustang_roof_3"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("fordmustang_roof_4"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("fordmustang_roof_5"),"Tuning 27")
	AddTextEntryByHash(GetHashKey("fordmustang_roof_6"),"Tuning 28")
	AddTextEntryByHash(GetHashKey("fordmustang_roof_7"),"Tuning 29")
	AddTextEntryByHash(GetHashKey("fordmustang_roof_8"),"Tuning 30")
	AddTextEntryByHash(GetHashKey("fordmustang_skirt_1"),"Tuning 31")
	AddTextEntryByHash(GetHashKey("fordmustang_wing_1"),"Tuning 32")
	AddTextEntryByHash(GetHashKey("fordmustang_wing_2"),"Tuning 33")
	AddTextEntryByHash(GetHashKey("fordmustang_wing_3"),"Tuning 34")
	AddTextEntryByHash(GetHashKey("fordmustang_wing_4"),"Tuning 35")
	AddTextEntryByHash(GetHashKey("fordmustang_wing_5"),"Tuning 36")
	AddTextEntryByHash(GetHashKey("fordmustang_wing_6"),"Tuning 37")

	AddTextEntryByHash(GetHashKey("lancerevolutionx_cage"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_exh1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_exh2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_exh3"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt_3"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt_4"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt_5"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt_6"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_split_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_split_2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_split_3"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing_1"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing_2"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing_3"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing_4"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing_5"),"Tuning 18")

	AddTextEntryByHash(GetHashKey("mazdarx7_bodyshell_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_3"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_4"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_5"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_6"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_7"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_8"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_9"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_3"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_4"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_5"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_6"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_7"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_8"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_9"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("mazdarx7_door_mirror_l"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("mazdarx7_door_mirror_r"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_1"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_2"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_3"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_4"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_5"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_6"),"Tuning 27")
	AddTextEntryByHash(GetHashKey("mazdarx7_hood_1"),"Tuning 28")
	AddTextEntryByHash(GetHashKey("mazdarx7_hood_2"),"Tuning 29")
	AddTextEntryByHash(GetHashKey("mazdarx7_hood_3"),"Tuning 30")
	AddTextEntryByHash(GetHashKey("mazdarx7_hood_4"),"Tuning 31")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_1"),"Tuning 32")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_2"),"Tuning 33")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_3"),"Tuning 34")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_4"),"Tuning 35")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_5"),"Tuning 36")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_6"),"Tuning 37")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_7"),"Tuning 38")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_8"),"Tuning 39")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirt_9"),"Tuning 40")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_1"),"Tuning 41")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_2"),"Tuning 42")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_3"),"Tuning 43")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_4"),"Tuning 44")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_5"),"Tuning 45")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_6"),"Tuning 46")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_7"),"Tuning 47")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_8"),"Tuning 48")

	AddTextEntryByHash(GetHashKey("nissangtr_arch_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("nissangtr_arch_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("nissangtr_bumf_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("nissangtr_bumf_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("nissangtr_bumf_3"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("nissangtr_bumr_1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("nissangtr_bumr_2"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("nissangtr_bumr_3"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("nissangtr_hood_1"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("nissangtr_skirt_1"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("nissangtr_skirt_2"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("nissangtr_skirt_3"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("nissangtr_wing_1"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("nissangtr_wing_2"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("nissangtr_wing_3"),"Tuning 15")

	AddTextEntryByHash(GetHashKey("nissangtrnismo_cage_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_cage_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_exh1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_hood"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_roof_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_roof_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_roof_3"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_roof_4"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_roof_5"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_roof_6"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_wing_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_wing_2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_wing_3"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_wing_4"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_wing_5"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_wing_6"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_wing_7"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("nissangtrnismo_wing_8"),"Tuning 18")

	AddTextEntryByHash(GetHashKey("skyliner34_bnt1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("skyliner34_bnt2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("skyliner34_bnt3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("skyliner34_bnt4"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("skyliner34_bnt5"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("skyliner34_bnt6"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("skyliner34_bumr1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("skyliner34_bumr2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("skyliner34_bumr3"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("skyliner34_bumr4"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("skyliner34_bumr5"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("skyliner34_bumr6"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("skyliner34_cage"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("skyliner34_exh_1"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("skyliner34_fenders"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("skyliner34_fenders2"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("skyliner34_fenders3"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("skyliner34_fenders4"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("skyliner34_stwheel1"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("skyliner342_wing_1"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("skyliner342_wing_2"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("skyliner34_seats1"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("skyliner34_seats2"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("skyliner34_skirt1"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("skyliner34_skirt2"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("skyliner34_skirt3"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("skyliner34_skirt4"),"Tuning 27")
	AddTextEntryByHash(GetHashKey("skyliner34_skirt5"),"Tuning 28")
	AddTextEntryByHash(GetHashKey("skyliner34_skirt6"),"Tuning 29")
	AddTextEntryByHash(GetHashKey("skyliner34_split1"),"Tuning 30")
	AddTextEntryByHash(GetHashKey("skyliner34_split2"),"Tuning 31")
	AddTextEntryByHash(GetHashKey("skyliner34_split3"),"Tuning 32")
	AddTextEntryByHash(GetHashKey("skyliner34_split4"),"Tuning 33")
	AddTextEntryByHash(GetHashKey("skyliner34_split5"),"Tuning 34")
	AddTextEntryByHash(GetHashKey("skyliner34_split6"),"Tuning 35")
	AddTextEntryByHash(GetHashKey("skyliner34_split7"),"Tuning 36")
	AddTextEntryByHash(GetHashKey("skyliner34_split8"),"Tuning 37")
	AddTextEntryByHash(GetHashKey("skyliner34_split9"),"Tuning 38")
	AddTextEntryByHash(GetHashKey("skyliner34_spoil_1"),"Tuning 39")
	AddTextEntryByHash(GetHashKey("skyliner34_spoil_2"),"Tuning 40")
	AddTextEntryByHash(GetHashKey("skyliner34_spoil_3"),"Tuning 41")
	AddTextEntryByHash(GetHashKey("skyliner34_spoil_4"),"Tuning 42")
	AddTextEntryByHash(GetHashKey("skyliner34_spoil_5"),"Tuning 43")
	AddTextEntryByHash(GetHashKey("skyliner34_spoil_6"),"Tuning 44")

	AddTextEntryByHash(GetHashKey("toyotasupra_bumprr"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("toyotasupra_cage_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("toyotasupra_cage_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("toyotasupra_roof"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_3"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_4"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_5"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_6"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_7"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_8"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_9"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_10"),"Tuning 14")

	AddTextEntryByHash(GetHashKey("bmwm3e36_bonnet_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("bmwm3e36_bonnet_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("bmwm3e36_bumr_f"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("bmwm3e36_bumr_r"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("bmwm3e36_cage"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("bmwm3e36_cage_1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("bmwm3e36_exh"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("bmwm3e36_exh1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("bmwm3e36_exh2"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("bmwm3e36_roof"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("bmwm3e36_skirt"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("bmwm3e36_wing_1"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("bmwm3e36_wing_2"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("bmwm3e36_wing_3"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("bmwm3e36_wing_4"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("bmwm3e36_wing_5"),"Tuning 16")

	AddTextEntryByHash(GetHashKey("mercedesgt63_bumpf_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("mercedesgt63_cage"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("mercedesgt63_wing_1"),"Tuning 03")

	AddTextEntryByHash(GetHashKey("ferrarif12_bumf_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("ferrarif12_bumr_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("ferrarif12_bumr_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("ferrarif12_chassis_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_3"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_4"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_5"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_6"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorlf_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorlf_2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorlf_3"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorlf_4"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorlf_5"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorlf_6"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorrf_1"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorrf_2"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorrf_3"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorrf_4"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorrf_5"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("ferrarif12_interior_doorrf_6"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("ferrarif12_rollcage_1"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("ferrarif12_skirt_1"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("ferrarif12_splitter_1"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("ferrarif12_spoiler_1"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("ferrarif12_stripes_bumf_1"),"Tuning 27")
	AddTextEntryByHash(GetHashKey("ferrarif12_stripes_chassis_1"),"Tuning 28")
	AddTextEntryByHash(GetHashKey("ferrarif12_stripes_doorlf_1"),"Tuning 29")
	AddTextEntryByHash(GetHashKey("ferrarif12_stripes_doorrf_1"),"Tuning 30")
	AddTextEntryByHash(GetHashKey("ferrarif12_wing_lf_1"),"Tuning 31")
	AddTextEntryByHash(GetHashKey("ferrarif12_wing_rf_1"),"Tuning 32")

	AddTextEntryByHash(GetHashKey("bmwi8_grill_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("bmwi8_grill_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("bmwi8_grill_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("bmwi8_grill_4"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("bmwi8_grill_5"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("bmwi8_grill_6"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("bmwi8_grill_7"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("bmwi8_rollcage"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("bmwi8_wing_1"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("bmwi8_wing_2"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("bmwi8_wing_3"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("bmwi8_wing_4"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("bmwi8_wing_5"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("bmwi8_wing_6"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("bmwi8_wing_7"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("bmwi8_wing_8"),"Tuning 16")

	AddTextEntryByHash(GetHashKey("nissangtr2_bumf"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("nissangtr2_bumr"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("nissangtr2_cw_bumf"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("nissangtr2_cw_bumr"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("nissangtr2_cw_skirt"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("nissangtr2_dba_bumf"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("nissangtr2_dba_bumr"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("nissangtr2_line_a"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("nissangtr2_line_b"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("nissangtr2_line_c"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("nissangtr2_line_d"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("nissangtr2_line_e"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("nissangtr2_mi_bon"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("nissangtr2_mi_bumf"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("nissangtr2_mi_bumf2"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("nissangtr2_mi_bumf3"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("nissangtr2_mi_skirt"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("nissangtr2_mi_wing"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("nissangtr2_mi_wing2"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("nissangtr2_skirt"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("nissangtr2_sv_bumf"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("nissangtr2_sv_exh"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("nissangtr2_sv_wing"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("nissangtr2_ts_bumf"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("nissangtr2_ts_bumr"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("nissangtr2_ts_exh"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("nissangtr2_ts_skirt"),"Tuning 27")
	AddTextEntryByHash(GetHashKey("nissangtr2_va_bon"),"Tuning 28")
	AddTextEntryByHash(GetHashKey("nissangtr2_va_bon2"),"Tuning 29")
	AddTextEntryByHash(GetHashKey("nissangtr2_va_boot"),"Tuning 30")
	AddTextEntryByHash(GetHashKey("nissangtr2_va_bumf"),"Tuning 31")
	AddTextEntryByHash(GetHashKey("nissangtr2_va_bumr"),"Tuning 32")
	AddTextEntryByHash(GetHashKey("nissangtr2_va_bumr2"),"Tuning 33")
	AddTextEntryByHash(GetHashKey("nissangtr2_va_wing"),"Tuning 34")
	AddTextEntryByHash(GetHashKey("nissangtr2_va_wing2"),"Tuning 35")
	AddTextEntryByHash(GetHashKey("nissangtr2_varis"),"Tuning 36")
	AddTextEntryByHash(GetHashKey("nissangtr2_varis2"),"Tuning 37")
	AddTextEntryByHash(GetHashKey("nissangtr2_wa_bumf"),"Tuning 38")
	AddTextEntryByHash(GetHashKey("nissangtr2_wa_bumr"),"Tuning 39")
	AddTextEntryByHash(GetHashKey("nissangtr2_wa_skirt"),"Tuning 40")
	AddTextEntryByHash(GetHashKey("nissangtr2_wa_wing"),"Tuning 41")
	AddTextEntryByHash(GetHashKey("nissangtr2_wfp_2"),"Tuning 42")
	AddTextEntryByHash(GetHashKey("nissangtr2_wfp_3"),"Tuning 43")
	AddTextEntryByHash(GetHashKey("nissangtr2_wfp_4"),"Tuning 44")
	AddTextEntryByHash(GetHashKey("nissangtr2_wlfp_2"),"Tuning 45")
	AddTextEntryByHash(GetHashKey("nissangtr2_wlfp_3"),"Tuning 46")
	AddTextEntryByHash(GetHashKey("nissangtr2_wlfp_4"),"Tuning 47")
	AddTextEntryByHash(GetHashKey("nissangtr2_wlrp_2"),"Tuning 48")
	AddTextEntryByHash(GetHashKey("nissangtr2_wlrp_3"),"Tuning 49")
	AddTextEntryByHash(GetHashKey("nissangtr2_wlrp_4"),"Tuning 50")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrfp_2"),"Tuning 51")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrfp_3"),"Tuning 52")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrfp_4"),"Tuning 53")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrp_2"),"Tuning 54")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrp_3"),"Tuning 55")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrp_4"),"Tuning 56")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrrp_2"),"Tuning 57")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrrp_3"),"Tuning 58")
	AddTextEntryByHash(GetHashKey("nissangtr2_wrrp_4"),"Tuning 59")

	AddTextEntryByHash(GetHashKey("civictyper_bumf"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("civictyper_bumf_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("civictyper_fk8"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("civictyper_hood"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("civictyper_ml"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("civictyper_mr"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("civictyper_wfp_2"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("civictyper_wfp_3"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("civictyper_wfp_4"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("civictyper_wlfp_2"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("civictyper_wlfp_3"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("civictyper_wlfp_4"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("civictyper_wlmp_2"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("civictyper_wlmp_3"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("civictyper_wlmp_4"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("civictyper_wrfp_2"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("civictyper_wrfp_3"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("civictyper_wrfp_4"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("civictyper_wrmp_2"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("civictyper_wrmp_3"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("civictyper_wrmp_4"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("civictyper_wrp_2"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("civictyper_wrp_3"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("civictyper_wrp_4"),"Tuning 24")

	AddTextEntryByHash(GetHashKey("subaruimpreza_otmp_cw"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("subaruimpreza_atmp_cw"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("subaruimpreza_kaput_k"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("subaruimpreza_etek_cw"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("subaruimpreza_sp_cr"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("subaruimpreza_sp_cw"),"Tuning 06")

	AddTextEntryByHash(GetHashKey("mustangfast_bonnetpins"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("mustangfast_bumf_gt350"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("mustangfast_bumperf"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("mustangfast_bumperr"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("mustangfast_dside_stp"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("mustangfast_exh_chrome"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("mustangfast_exh_titanium"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("mustangfast_grille1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("mustangfast_grille2"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("mustangfast_hood_carbon"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("mustangfast_hood_drag"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("mustangfast_hood_gt350"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("mustangfast_hood_Scoop"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("mustangfast_livery1"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("mustangfast_livery2"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("mustangfast_livery3"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("mustangfast_pside_stp"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("mustangfast_rollcage"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("mustangfast_sidestp"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("mustangfast_vents"),"Tuning 20")

	AddTextEntryByHash(GetHashKey("acuransx_bodykit_01"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("acuransx_bodykit_02"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("acuransx_bumf_01"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("acuransx_bumr"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("acuransx_livery_body"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("acuransx_livery_bumr"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("acuransx_livery_door_l"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("acuransx_livery_door_r"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("acuransx_livery_f"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("acuransx_livery_r"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("acuransx_spoil_01"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("acuransx_spoil_02"),"Tuning 12")

	AddTextEntryByHash(GetHashKey("nissangtr3_arch_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("nissangtr3_arch_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("nissangtr3_bumf_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("nissangtr3_bumf_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("nissangtr3_bumf_3"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("nissangtr3_bumr_1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("nissangtr3_bumr_2"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("nissangtr3_bumr_3"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("nissangtr3_hood_1"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("nissangtr3_skirt_1"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("nissangtr3_skirt_2"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("nissangtr3_skirt_3"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("nissangtr3_wing_1"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("nissangtr3_wing_2"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("nissangtr3_wing_3"),"Tuning 15")

	AddTextEntryByHash(GetHashKey("ferrariitalia_bnt1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("ferrariitalia_bnt2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("ferrariitalia_bnt3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("ferrariitalia_bumr1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("ferrariitalia_bumr2"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("ferrariitalia_ext1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("ferrariitalia_int_roll1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("ferrariitalia_int_roll2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("ferrariitalia_skirt1"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("ferrariitalia_skirt2"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("ferrariitalia_skirt3"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("ferrariitalia_skirt4"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("ferrariitalia_split1"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("ferrariitalia_split2"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("ferrariitalia_split3"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("ferrariitalia_spoil_1"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("ferrariitalia_spoil_2"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("ferrariitalia_spoil_3"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("ferrariitalia_spoil_4"),"Tuning 19")

	AddTextEntryByHash(GetHashKey("skyliner342_wing_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("skyliner342_wing_2"),"Tuning 02")

	AddTextEntryByHash(GetHashKey("mazdarx72_spoiler_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("mazdarx72_spoiler_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("mazdarx72_spoiler_3"),"Tuning 03")

	AddTextEntryByHash(GetHashKey("bmwm5e34_bumperf"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("bmwm5e34_bumperr"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("bmwm5e34_rollcage"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("bmwm5e34_skirt"),"Tuning 04")

	AddTextEntryByHash(GetHashKey("golfmk7_rollcage"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("golfmk7_rollcage_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("golfmk7_wing_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("golfmk7_wing_2"),"Tuning 04")

	AddTextEntryByHash(GetHashKey("jeepcherokee_cage"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("jeepcherokee_rooflight"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("jeepcherokee_skirt"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("jeepcherokee_wing_1"),"Tuning 04")

	AddTextEntryByHash(GetHashKey("porsche911_bixenon_lamps"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("porsche911_bon1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("porsche911_bon2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("porsche911_bon3"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("porsche911_bon4"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("porsche911_bon5"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("porsche911_exh1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("porsche911_exh2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("porsche911_exh3"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("porsche911_exh4"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("porsche911_exh5"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("porsche911_fbmpr1"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("porsche911_fbmpr2"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("porsche911_fbmpr3"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("porsche911_fbmpr4"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("porsche911_fbmpr5"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("porsche911_fbmpr6"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("porsche911_fbmpr7"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("porsche911_fender1"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("porsche911_fender2"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("porsche911_fender3"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("porsche911_int_decor1"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("porsche911_int_decor2"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("porsche911_int_decor3"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("porsche911_int_decor5"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("porsche911_int_decor6"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("porsche911_lap_timer"),"Tuning 27")
	AddTextEntryByHash(GetHashKey("porsche911_lcd1"),"Tuning 28")
	AddTextEntryByHash(GetHashKey("porsche911_lcd2"),"Tuning 29")
	AddTextEntryByHash(GetHashKey("porsche911_lcd3"),"Tuning 30")
	AddTextEntryByHash(GetHashKey("porsche911_mir1_l"),"Tuning 31")
	AddTextEntryByHash(GetHashKey("porsche911_mir1_r"),"Tuning 32")
	AddTextEntryByHash(GetHashKey("porsche911_mir2_l"),"Tuning 33")
	AddTextEntryByHash(GetHashKey("porsche911_mir2_r"),"Tuning 34")
	AddTextEntryByHash(GetHashKey("porsche911_rbmpr1"),"Tuning 35")
	AddTextEntryByHash(GetHashKey("porsche911_rbmpr2"),"Tuning 36")
	AddTextEntryByHash(GetHashKey("porsche911_rbmpr3"),"Tuning 37")
	AddTextEntryByHash(GetHashKey("porsche911_rbmpr4"),"Tuning 38")
	AddTextEntryByHash(GetHashKey("porsche911_rollbar"),"Tuning 39")
	AddTextEntryByHash(GetHashKey("porsche911_rollbar2"),"Tuning 40")
	AddTextEntryByHash(GetHashKey("porsche911_roof_vent1"),"Tuning 41")
	AddTextEntryByHash(GetHashKey("porsche911_roof_vent2"),"Tuning 42")
	AddTextEntryByHash(GetHashKey("porsche911_roof3"),"Tuning 43")
	AddTextEntryByHash(GetHashKey("porsche911_seat_bucket"),"Tuning 44")
	AddTextEntryByHash(GetHashKey("porsche911_seat_sport"),"Tuning 45")
	AddTextEntryByHash(GetHashKey("porsche911_side_vents"),"Tuning 46")
	AddTextEntryByHash(GetHashKey("porsche911_skirt1"),"Tuning 47")
	AddTextEntryByHash(GetHashKey("porsche911_skirt2"),"Tuning 48")
	AddTextEntryByHash(GetHashKey("porsche911_skirt3"),"Tuning 49")
	AddTextEntryByHash(GetHashKey("porsche911_skirt4"),"Tuning 50")
	AddTextEntryByHash(GetHashKey("porsche911_spoil_gt3"),"Tuning 51")
	AddTextEntryByHash(GetHashKey("porsche911_spoil_hidnfrce"),"Tuning 52")
	AddTextEntryByHash(GetHashKey("porsche911_spoil_lip"),"Tuning 53")
	AddTextEntryByHash(GetHashKey("porsche911_spoil_race"),"Tuning 54")
	AddTextEntryByHash(GetHashKey("porsche911_steer1"),"Tuning 55")
	AddTextEntryByHash(GetHashKey("porsche911_steer2"),"Tuning 56")

	AddTextEntryByHash(GetHashKey("toyotasupra2_cage1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("toyotasupra2_cage2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("toyotasupra2_cage3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("toyotasupra2_cage4"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("toyotasupra2_cage5"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("toyotasupra2_cage6"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("toyotasupra2_cage7"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("toyotasupra2_door1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("toyotasupra2_door2"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("toyotasupra2_door3"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("toyotasupra2_door4"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("toyotasupra2_door5"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("toyotasupra2_door6"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("toyotasupra2_door7"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("toyotasupra2_door8"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("toyotasupra2_exh1"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("toyotasupra2_exh2"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("toyotasupra2_exh3"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("toyotasupra2_exh4"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("toyotasupra2_exh5"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("toyotasupra2_exh6"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("toyotasupra2_exh7"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood1"),"Tuning 23")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood2"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood3"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood4"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood5"),"Tuning 27")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood6"),"Tuning 28")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood7"),"Tuning 29")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood8"),"Tuning 30")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood9"),"Tuning 31")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood10"),"Tuning 32")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood11"),"Tuning 33")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood12"),"Tuning 34")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood13"),"Tuning 35")
	AddTextEntryByHash(GetHashKey("toyotasupra2_hood14"),"Tuning 36")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing1"),"Tuning 37")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing2"),"Tuning 38")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing3"),"Tuning 39")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing4"),"Tuning 40")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing5"),"Tuning 41")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing6"),"Tuning 42")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing7"),"Tuning 43")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing8"),"Tuning 44")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing9"),"Tuning 45")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing10"),"Tuning 46")
	AddTextEntryByHash(GetHashKey("toyotasupra2_wing11"),"Tuning 47")

	AddTextEntryByHash(GetHashKey("350z_rollcage"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("350z_skirt"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("350z_wing_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("350z_wing_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("350z_wing_3"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("350z_wing_4"),"Tuning 06")
end)